[package]
name = "arm64-mask-gen"
authors = ["Xliee <fran@logicode.es>"]
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
regex = "1.0"
anyhow = "1.0"
keystone-engine = { version = "0.9", optional = true }

[features]
default = []
keystone = ["keystone-engine"]
